# Generated by Django 4.2.20 on 2025-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptinfo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
