# Generated by Django 4.2.20 on 2025-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_scriptinfo_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinfo',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='ScriptContent',
        ),
    ]
