# Generated by Django 4.2.20 on 2025-04-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_scriptinfo_text_delete_scriptcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
