# Generated by Django 4.2.20 on 2025-04-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptInfo',
            fields=[
                ('script_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='home.scriptinfo')),
            ],
        ),
    ]
