# Generated by Django 4.2.20 on 2025-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptcontent',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='scriptcontent',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='scriptinfo',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scriptinfo',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
