# Generated by Django 4.2.20 on 2025-04-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_scriptcontent_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptContent',
        ),
        migrations.DeleteModel(
            name='ScriptInfo',
        ),
    ]
